sudo: false
language: rust
rust:
  - nightly
services:
  - docker

jobs:
  include:
    - stage: install components
      script:
        - rustup component add clippy
        - rustup component add rustfmt
      workspaces:
        create:
          name: static_analysis_ws
    - stage: clippy backend
      workspaces:
        use: static_analysis_ws
      before_script: cd backend/
      script:
        - cargo +nightly clippy
    - stage: fmt backend
      workspaces:
        use: static_analysis_ws
      before_script: cd backend/
      script:
        - cargo +nightly fmt
    - stage: clippy frontend
      workspaces:
        use: static_analysis_ws
      before_script: cd frontend/
      script:
        - cargo +nightly clippy
    - stage: fmt frontend
      workspaces:
        use: static_analysis_ws
      before_script: cd frontend/
      script:
        - cargo +nightly fmt
    - stage: backend
      before_script: cd backend/ 
      script: cargo +nightly build
    - stage: frontend
      script: docker-compose build 

stages:
  - install components
  - clippy backend
  - fmt backend
  - clippy frontend
  - fmt frontend
  - backend
  - frontend

